paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      description: Devuelve una lista de todos los productos disponibles.
      tags: [Productos]
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'

    post:
      summary: Crear un nuevo producto
      description: Registra un nuevo producto en el sistema.
      tags: [Productos]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '200':
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'

  /api/products/{id}:
    get:
      summary: Obtener producto por ID
      description: Devuelve los detalles de un producto específico.
      tags: [Productos]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID del producto
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'

    put:
      summary: Actualizar producto
      description: Actualiza la información de un producto existente.
      tags: [Productos]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '200':
          description: Producto actualizado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'

    delete:
      summary: Eliminar producto
      description: Elimina un producto del sistema.
      tags: [Productos]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID del producto
      responses:
        '204':
          description: Producto eliminado exitosamente

components:
  schemas:
    ProductRequest:
      type: object
      properties:
        name:
          type: string
          example: Cuenta Corriente
        description:
          type: string
          example: Cuenta bancaria con línea de crédito
        type:
          type: string
          enum: [CUENTA_CORRIENTE, CUENTA_VISTA, CUENTA_AHORRO]
        status:
          type: string
          enum: [ACTIVO, INACTIVO]
      required:
        - name
        - type
        - status

    ProductResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Cuenta Corriente
        description:
          type: string
          example: Cuenta bancaria con línea de crédito
        type:
          type: string
          example: CUENTA_CORRIENTE
        status:
          type: string
          example: ACTIVO
